### ISSUE TITLE
OOM problem

### ISSUE THREAD

**Issue by subhansb8** [Niopek-Lab/ProDomino#4]
Dear Authors,

Thank you for sharing the code, btw, I have a problem with OOM:

RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

After this command:
embed = embedder.predict_embedding(seq)
pred = model.predict_insertion_sites(embed)

Could you solve the problem,? I use 8 GB GPU ( I know it's not enough, but previous DL (using ESM2, 3GB) could be used with 8 GB GPU.

Thanks

**Comment by mengdy0217** [comment]
Hello, 8GB is not enough. The graphics card memory must be at least 24GB. After I changed it, the error disappeared.

**Comment by lzygitk7** [comment]
I assume in the embedding step, the `fsdp` is not required for single light inference.
